name: Post to Bluesky every 5 minutes

on:
  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install atproto requests

      - name: Run script
        env:
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}

        run: |
          python post_to_bluesky_test.py
